# Generated by Django 5.0.1 on 2024-01-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('task', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('completed', 'completed'), ('pending', 'pending')], default='pending', max_length=20)),
            ],
        ),
    ]
